name: Build APK Spaceness

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code Spaceness
        uses: actions/checkout@v4

      - name: Build automatique avec l action officielle Kivy
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Telecharger l APK de Spaceness
        uses: actions/upload-artifact@v4
        with:
          name: Spaceness-APK
          path: bin/*.apk
          
